config/routes.rb
KnowInfinite::Application.routes.draw do

  

  root :to => "sessions#login"
  match "courses/browse", :to=> "courses#browse", :via=>:get
  match "signup", :to => "users#new", :via=>:get
  post "users/create"
  match "login", :to => "sessions#login", :via=>:get
  match "logout", :to => "sessions#logout", :via=>:get
  match "home", :to => "sessions#home", :via=>:get
  match "profile", :to => "sessions#profile", :via=>:get
  match "setting", :to => "sessions#setting", :via=>:get
  match "login_attempt", :to => "sessions#login_attempt", :via=>:post

  resources :nuggets

  resources :courses do
    member do
      get 'view'
    end
  end

  match ':controller(/:action(/:id))', :via => :get
  match ':controller(/:action(/:id))', :via => :post
end

app/models/nugget.rb
class Nugget < ActiveRecord::Base
	belongs_to :course
	acts_as_list :scope => :course

	#named scopes
	scope :sorted, lambda { order("nuggets.position ASC") }
end

app/controllers/nuggets_controller.rb
class NuggetsController < ApplicationController
  before_action :confirm_logged_in
  before_action :set_nugget, only: [:show, :edit, :update, :destroy]
  before_action :set_course, only: [:index, :new, :edit, :update, :delete, :create]

  # GET /nuggets
  # GET /nuggets.json
  def index
    @nuggets = @course.nuggets.sorted
  end

  # GET /nuggets/1
  # GET /nuggets/1.json
  def show
  end

  # GET /nuggets/new
  def new
    @nugget = Nugget.new
  end

  # GET /nuggets/1/edit
  def edit
  end

  # POST /nuggets
  # POST /nuggets.json
  def create
    @nugget = Nugget.new(nugget_params)
    @nugget.course_id = @course.id
    @nugget.user_id = session[:user_id]

    respond_to do |format|
      if @nugget.save
        format.html { redirect_to @nugget, notice: 'Nugget was successfully created.' }
        format.json { render action: 'show', status: :created, location: @nugget }
      else
        format.html { render action: 'new' }
        format.json { render json: @nugget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nuggets/1
  # PATCH/PUT /nuggets/1.json
  def update
    respond_to do |format|
      if @nugget.update(nugget_params)
        format.html { redirect_to @nugget, notice: 'Nugget was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @nugget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nuggets/1
  # DELETE /nuggets/1.json
  def destroy
    @nugget.destroy
    respond_to do |format|
      format.html { redirect_to nuggets_url(:course_id => @nugget.course_id)}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nugget
      @nugget = Nugget.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def nugget_params
      params.require(:nugget).permit(:name, :description, :course_id, :user_id, :position)
    end

    def set_course
      if params[:course_id]
        @course = Course.find(params[:course_id])
      elsif params[:nugget][:course_id]
        @course = Course.find(params[:nugget][:course_id])
      else
        puts "Could not find course_id"
      end
    end
end

app/helpers/nuggets_helper.rb
module NuggetsHelper
end

app/views/nuggets/_form.html.erb
<%= form_for @nugget, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :position, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :position, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
      <%= f.hidden_field :course_id, :value => @course.id %>
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                nuggets_path, :class => 'btn' %>
  </div>
<% end %>

app/views/nuggets/edit.html.erb
<%- model_class = Nugget -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/nuggets/index.html.erb
<%- model_class = Nugget -%>
<div class="page-header">
  <h1><%=t '.title', :default => @course.name %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:position) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @nuggets.each do |nugget| %>
      <tr>
        <td><%= link_to nugget.name, nugget_path(nugget) %></td>
        <td><%= nugget.description %></td>
        <td><%= nugget.position %></td>
        <td><%=l nugget.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_nugget_path(nugget, :course_id => nugget.course_id), :class => 'btn btn-primary' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      nugget_path(nugget),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to("Add New", {:controller=> 'nuggets', :action => 'new', :course_id => @course.id}, :class => 'btn btn-primary' ) %>

app/views/nuggets/new.html.erb
<%- model_class = Nugget -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/nuggets/show.html.erb
<%- model_class = Nugget -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @nugget.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @nugget.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:position) %>:</strong></dt>
  <dd><%= @nugget.position %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              nuggets_path(:course_id => @nugget.course_id), :class => 'btn'  %>
<%= link_to("Edit", {:controller=> 'nuggets', :action => 'edit', :course_id => @nugget.course_id}, :class => 'btn' ) %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              nugget_path(@nugget),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :course_id => @nugget.course_id },
              :class => 'btn btn-danger' %>
</div>